#define SEMICOLON_TOK ';'
#define COMMA_TOK ','
#define LCRLY_TOK '{'
#define RCRLY_TOK '}'
#define LPAREN_TOK '('
#define RPAREN_TOK ')'
#define INT_TOK 1000
#define MAIN_TOK 1001
#define ID_TOK 1002
#define tk_EOI 1003
#define tk_Mul '*'
#define tk_Div '/'
#define tk_Mod '%'
#define tk_Add '+'
#define tk_Sub '-'
#define tk_Not '!'
#define tk_Lss '<'
#define tk_Leq '<='
#define tk_Gtr '>'
#define tk_Geq '>='
#define tk_Eq '=='
#define tk_Neq '!='
#define tk_Assign '=' 
#define tk_And '&&' 
#define tk_Or '||' 
#define tk_If 1004
#define tk_Else 1005 
#define tk_While 1006
#define tk_Print 1007
#define tk_Putc 1008 
#define tk_Ident 1009 
#define tk_Integer 1010 
#define tk_Hash '#'
#define tk_dot '.'  
#define tk_Lsqbr '[' 
#define tk_Rsqbr ']' 
#define tk_do 1011
#define tk_break 1012 
#define tk_Continue 1013
#define tk_Float 1014 
#define tk_Double 1015 
#define tk_return 1016 
#define tk_Char 1017
#define tk_Case 1018
#define tk_Sizeof 1019 
#define tk_Long 1020 
#define tk_Short 1021
#define tk_Typedef 1022 
#define tk_Switch 1023
#define tk_Unsigned 1024
#define tk_Void 1025
#define tk_static 1026
#define tk_struct 1027 
#define tk_goto 1028
#define tk_BitwiseAnd '&'
#define tk_BitwiseOr '|'
#define tk_String 1029